name: Cairo M31 workflow
on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - auto_merge_enabled

  merge_group:
    types:
      - checks_requested

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: false
      - uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt
          profile: minimal
          toolchain: nightly-2024-01-04
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly-2024-01-04 test --release

  format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt
          toolchain: nightly-2024-01-04
      - uses: Swatinem/rust-cache@v2
      - run: scripts/rust_fmt.sh --check

  clippy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          components: clippy
          toolchain: nightly-2024-01-04
      - uses: Swatinem/rust-cache@v2
      - run: scripts/clippy.sh
